"""add phone number

Revision ID: 202e95aafe7a
Revises: b79624a63010
Create Date: 2023-08-03 17:34:15.626850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202e95aafe7a'
down_revision = 'b79624a63010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', 
            sa.String(), nullable=False))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    pass
    # ### end Alembic commands ###
